export const GET_CITY = "GET_CITY"
export const GET_POINT = "GET_POINT"
export const SET_CITY = "SET_CITY"
export const SET_POINT = "SET_POINT"
export const GET_CAR = "GET_CAR"
export const SET_CAR = "SET_CAR"